CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Teams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
);

CREATE TABLE "CheckIns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeamId" integer NOT NULL,
    "MoodRating" integer NOT NULL,
    "StressLevel" integer NOT NULL,
    "Notes" character varying(500),
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_CheckIns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CheckIns_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CheckIns_SubmittedAt" ON "CheckIns" ("SubmittedAt");

CREATE INDEX "IX_CheckIns_TeamId" ON "CheckIns" ("TeamId");

CREATE INDEX "IX_CheckIns_TeamId_SubmittedAt" ON "CheckIns" ("TeamId", "SubmittedAt");

CREATE UNIQUE INDEX "IX_Teams_Name" ON "Teams" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250601035832_InitialCreate', '8.0.0');

COMMIT;

